<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Assignment MVA Multiple Logistic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="HeartAttackMLog_files/libs/clipboard/clipboard.min.js"></script>
<script src="HeartAttackMLog_files/libs/quarto-html/quarto.js"></script>
<script src="HeartAttackMLog_files/libs/quarto-html/popper.min.js"></script>
<script src="HeartAttackMLog_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HeartAttackMLog_files/libs/quarto-html/anchor.min.js"></script>
<link href="HeartAttackMLog_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HeartAttackMLog_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HeartAttackMLog_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HeartAttackMLog_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HeartAttackMLog_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment MVA Multiple Logistic Regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
</section>
<section id="group-member" class="level1">
<h1>Group Member</h1>
<p>1 Ijlal Syamim bin Mohd Basri</p>
<p>2 Muhammad Naim bin Deraman</p>
<p>3 Mohd Aslam bin Ariffin</p>
<p>4 ’Abdul Muntaqim bin Abu Bakar</p>
<p>5 Mohd Fahmin bin Kamarul Zaman</p>
<p>This is our team members:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="gambar.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">EOH Members</figcaption>
</figure>
</div>
</section>
<section id="dataset" class="level1">
<h1>Dataset</h1>
<p>We will use heart attack predition dataset obtained from kaggle.com. The reference of the dataset is as below:</p>
<p>age: Age of the patient</p>
<p>sex: Sex of the patient</p>
<p>cp: Chest pain type, 0 = Typical Angina, 1 = Atypical Angina, 2 = Non-anginal Pain, 3 = Asymptomatic</p>
<p>trtbps: Resting blood pressure (in mm Hg)</p>
<p>chol: Cholestoral in mg/dl fetched via BMI sensor</p>
<p>fbs: (fasting blood sugar &gt; 120 mg/dl), 1 = True, 0 = False</p>
<p>restecg: Resting electrocardiographic results, 0 = Normal, 1 = ST-T wave normality, 2 = Left ventricular hypertrophy</p>
<p>thalachh: Maximum heart rate achieved</p>
<p>oldpeak: Previous peak</p>
<p>slp: Slope</p>
<p>caa: Number of major vessels</p>
<p>thall: Thalium Stress Test result ~ (0,3)</p>
<p>exng: Exercise induced angina ~ 1 = Yes, 0 = No</p>
<p>output: Heart Attack ~ 1 = yes, 0 = No</p>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<p>We will employ the Multiple Logistic Regression from the dataset.</p>
<p>We want to predict the relationship between heart attack event with its associated factors. All variables will be used but we will select few variables for the purpose of modelling according to few criteria, such as clinically significant data, data which is highly spelled out in literature and clinical expert opinion.</p>
<p>Assumptions : independence of errors/observations, correctly specified models, correct functional forms, absence of multicollinearity and fixed errors (measured without error)</p>
</section>
<section id="workflow-analysis" class="level2">
<h2 class="anchored" data-anchor-id="workflow-analysis">Workflow Analysis</h2>
<p>Goals of model building in our regression models are:</p>
<p>-To find best fitting model -To develop the most parsimonious model -To develop a biologically sound model</p>
<p>We will apply these steps to achieved our goal 1) Data wrangling 2) Univariable Selection One of the variables is the dependent variable. The dependent variable is binary in nature. The other variable is the independent variable.The independent variable can be a numerical variable or can be a categorical variable. The conditional mean of the dependent variable Y given x when the logistic distribution is used (in a case of univariable, model has only 1 predictor) is:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="simplelog.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">slog</figcaption>
</figure>
</div>
<ol start="3" type="1">
<li>Variable selection -does not consider p-value&lt;0.25 The conditional mean of the dependent variable Y given x when the logistic distribution is used (in a case of univariable, model has k predictor) is writen as a logistic model :</li>
</ol>
<p><img src="logisticmodel1.jpg" class="img-fluid" alt="logistic model"> Where:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="logisticmodel2.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">log model</figcaption>
</figure>
</div>
<ol start="4" type="1">
<li><p>Check for multicollinearity</p></li>
<li><p>Check 2 way interaction</p></li>
<li><p>Assess goodness of fit model</p></li>
<li><p>Establish final model</p></li>
<li><p>Data presentation and Interpretation</p></li>
</ol>
</section>
<section id="steps" class="level2">
<h2 class="anchored" data-anchor-id="steps">Steps</h2>
</section>
</section>
<section id="load-library" class="level1">
<h1>Load Library</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'broom' was built under R version 4.3.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'here' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at C:/Users/User/Documents/R Project DrPH/MyRepoR</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'psych' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'

The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'corrplot' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'caret' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lattice' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'caret'

The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jpeg)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gtsummary' was built under R version 4.3.2</code></pre>
</div>
</div>
</section>
<section id="read-data" class="level1">
<h1>Read data</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>heart <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">'raw_data'</span>, <span class="st">'heart.csv'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="view-our-data-using-str-function" class="level1">
<h1>view our data using str function</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(heart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   303 obs. of  14 variables:
 $ age     : int  63 37 41 56 57 57 56 44 52 57 ...
 $ sex     : int  1 1 0 1 0 1 0 1 1 1 ...
 $ cp      : int  3 2 1 1 0 0 1 1 2 2 ...
 $ trtbps  : int  145 130 130 120 120 140 140 120 172 150 ...
 $ chol    : int  233 250 204 236 354 192 294 263 199 168 ...
 $ fbs     : int  1 0 0 0 0 0 0 0 1 0 ...
 $ restecg : int  0 1 0 1 1 1 0 1 1 1 ...
 $ thalachh: int  150 187 172 178 163 148 153 173 162 174 ...
 $ exng    : int  0 0 0 0 1 0 0 0 0 0 ...
 $ oldpeak : num  2.3 3.5 1.4 0.8 0.6 0.4 1.3 0 0.5 1.6 ...
 $ slp     : int  0 0 2 2 2 1 1 2 2 2 ...
 $ caa     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ thall   : int  1 2 2 2 2 1 2 3 3 2 ...
 $ output  : int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
</section>
<section id="check-for-null-value.-to-be-safe-if-there-is-missing-values-in-our-data" class="level1">
<h1>check for null value. to be safe if there is missing values in our data</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(heart))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age      sex       cp   trtbps     chol      fbs  restecg thalachh 
       0        0        0        0        0        0        0        0 
    exng  oldpeak      slp      caa    thall   output 
       0        0        0        0        0        0 </code></pre>
</div>
</div>
</section>
<section id="check-for-duplicates.-remove-if-detected" class="level1">
<h1>check for duplicates. remove if detected</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>duplicated_rows <span class="ot">&lt;-</span> <span class="fu">duplicated</span>(heart)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>duplicated_rows_data <span class="ot">&lt;-</span> heart[duplicated_rows, ]</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(duplicated_rows_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age sex cp trtbps chol fbs restecg thalachh exng oldpeak slp caa thall
165  38   1  2    138  175   0       1      173    0       0   2   4     2
    output
165      0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>heart1 <span class="ot">&lt;-</span> heart[<span class="sc">!</span>duplicated_rows, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our data is considered clean now. Let us proceed with descriptive analysis</p>
</section>
<section id="describe-data" class="level1">
<h1>describe data</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(heart1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         vars   n   mean    sd median trimmed   mad min   max range  skew
age         1 302  54.42  9.05   55.5   54.60  9.64  29  77.0  48.0 -0.20
sex         2 302   0.68  0.47    1.0    0.73  0.00   0   1.0   1.0 -0.78
cp          3 302   0.96  1.03    1.0    0.86  1.48   0   3.0   3.0  0.49
trtbps      4 302 131.60 17.56  130.0  130.40 14.83  94 200.0 106.0  0.71
chol        5 302 246.50 51.75  240.5  243.71 47.44 126 564.0 438.0  1.14
fbs         6 302   0.15  0.36    0.0    0.06  0.00   0   1.0   1.0  1.96
restecg     7 302   0.53  0.53    1.0    0.52  0.74   0   2.0   2.0  0.17
thalachh    8 302 149.57 22.90  152.5  150.88 22.98  71 202.0 131.0 -0.53
exng        9 302   0.33  0.47    0.0    0.29  0.00   0   1.0   1.0  0.73
oldpeak    10 302   1.04  1.16    0.8    0.86  1.19   0   6.2   6.2  1.25
slp        11 302   1.40  0.62    1.0    1.46  1.48   0   2.0   2.0 -0.50
caa        12 302   0.72  1.01    0.0    0.53  0.00   0   4.0   4.0  1.28
thall      13 302   2.31  0.61    2.0    2.36  0.00   0   3.0   3.0 -0.48
output     14 302   0.46  0.50    0.0    0.45  0.00   0   1.0   1.0  0.17
         kurtosis   se
age         -0.55 0.52
sex         -1.40 0.03
cp          -1.20 0.06
trtbps       0.86 1.01
chol         4.40 2.98
fbs          1.85 0.02
restecg     -1.37 0.03
thalachh    -0.10 1.32
exng        -1.47 0.03
oldpeak      1.49 0.07
slp         -0.65 0.04
caa          0.72 0.06
thall        0.25 0.04
output      -1.98 0.03</code></pre>
</div>
</div>
</section>
<section id="summary" class="level1">
<h1>summary</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(heart1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age             sex               cp             trtbps     
 Min.   :29.00   Min.   :0.0000   Min.   :0.0000   Min.   : 94.0  
 1st Qu.:48.00   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:120.0  
 Median :55.50   Median :1.0000   Median :1.0000   Median :130.0  
 Mean   :54.42   Mean   :0.6821   Mean   :0.9636   Mean   :131.6  
 3rd Qu.:61.00   3rd Qu.:1.0000   3rd Qu.:2.0000   3rd Qu.:140.0  
 Max.   :77.00   Max.   :1.0000   Max.   :3.0000   Max.   :200.0  
      chol            fbs           restecg          thalachh    
 Min.   :126.0   Min.   :0.000   Min.   :0.0000   Min.   : 71.0  
 1st Qu.:211.0   1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:133.2  
 Median :240.5   Median :0.000   Median :1.0000   Median :152.5  
 Mean   :246.5   Mean   :0.149   Mean   :0.5265   Mean   :149.6  
 3rd Qu.:274.8   3rd Qu.:0.000   3rd Qu.:1.0000   3rd Qu.:166.0  
 Max.   :564.0   Max.   :1.000   Max.   :2.0000   Max.   :202.0  
      exng           oldpeak           slp             caa        
 Min.   :0.0000   Min.   :0.000   Min.   :0.000   Min.   :0.0000  
 1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:1.000   1st Qu.:0.0000  
 Median :0.0000   Median :0.800   Median :1.000   Median :0.0000  
 Mean   :0.3278   Mean   :1.043   Mean   :1.397   Mean   :0.7185  
 3rd Qu.:1.0000   3rd Qu.:1.600   3rd Qu.:2.000   3rd Qu.:1.0000  
 Max.   :1.0000   Max.   :6.200   Max.   :2.000   Max.   :4.0000  
     thall           output     
 Min.   :0.000   Min.   :0.000  
 1st Qu.:2.000   1st Qu.:0.000  
 Median :2.000   Median :0.000  
 Mean   :2.315   Mean   :0.457  
 3rd Qu.:3.000   3rd Qu.:1.000  
 Max.   :3.000   Max.   :1.000  </code></pre>
</div>
</div>
</section>
<section id="no-id-so-add-one-more-column" class="level1">
<h1>No ID, so add one more column</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>heart1<span class="sc">$</span>ID <span class="ot">&lt;-</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(heart1))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>heart1 <span class="ot">&lt;-</span> heart1[, <span class="fu">c</span>(<span class="st">"ID"</span>, <span class="fu">names</span>(heart1)[<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(heart1) <span class="sc">==</span> <span class="st">"ID"</span>)])]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="transform-data-as-categorical" class="level1">
<h1>Transform data as categorical</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>heart1<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">factor</span>(heart1<span class="sc">$</span>sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>))</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>heart1<span class="sc">$</span>cp <span class="ot">&lt;-</span> <span class="fu">factor</span>(heart1<span class="sc">$</span>cp, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Type 0"</span>, <span class="st">"Type 1"</span>, <span class="st">"Type 2"</span>, <span class="st">"Type 3"</span>))</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>heart1<span class="sc">$</span>fbs <span class="ot">&lt;-</span> <span class="fu">factor</span>(heart1<span class="sc">$</span>fbs, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"False"</span>, <span class="st">"True"</span>))</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>heart1<span class="sc">$</span>restecg <span class="ot">&lt;-</span> <span class="fu">factor</span>(heart1<span class="sc">$</span>restecg, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Type 0"</span>, <span class="st">"Type 1"</span>, <span class="st">"Type 2"</span>))</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>heart1<span class="sc">$</span>exng <span class="ot">&lt;-</span> <span class="fu">factor</span>(heart1<span class="sc">$</span>exng, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>heart1<span class="sc">$</span>thall <span class="ot">&lt;-</span> <span class="fu">factor</span>(heart1<span class="sc">$</span>thall, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Type 0"</span>, <span class="st">"Type 1"</span>, <span class="st">"Type 2"</span>, <span class="st">"Type 3"</span>))</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>heart1<span class="sc">$</span>caa <span class="ot">&lt;-</span> <span class="fu">factor</span>(heart1<span class="sc">$</span>caa, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Type 0"</span>, <span class="st">"Type 1"</span>, <span class="st">"Type 2"</span>, <span class="st">"Type 3"</span>, <span class="st">"Type 4"</span>))</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>heart1<span class="sc">$</span>slp <span class="ot">&lt;-</span> <span class="fu">factor</span>(heart1<span class="sc">$</span>slp, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Type 0"</span>, <span class="st">"Type 1"</span>, <span class="st">"Type 2"</span>))</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>heart1<span class="sc">$</span>output <span class="ot">&lt;-</span> <span class="fu">factor</span>(heart1<span class="sc">$</span>output, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(heart1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       ID              age            sex           cp          trtbps     
 Min.   :  1.00   Min.   :29.00   Female: 96   Type 0:143   Min.   : 94.0  
 1st Qu.: 76.25   1st Qu.:48.00   Male  :206   Type 1: 50   1st Qu.:120.0  
 Median :151.50   Median :55.50                Type 2: 86   Median :130.0  
 Mean   :151.50   Mean   :54.42                Type 3: 23   Mean   :131.6  
 3rd Qu.:226.75   3rd Qu.:61.00                             3rd Qu.:140.0  
 Max.   :302.00   Max.   :77.00                             Max.   :200.0  
      chol          fbs        restecg       thalachh      exng    
 Min.   :126.0   False:257   Type 0:147   Min.   : 71.0   No :203  
 1st Qu.:211.0   True : 45   Type 1:151   1st Qu.:133.2   Yes: 99  
 Median :240.5               Type 2:  4   Median :152.5            
 Mean   :246.5                            Mean   :149.6            
 3rd Qu.:274.8                            3rd Qu.:166.0            
 Max.   :564.0                            Max.   :202.0            
    oldpeak          slp          caa         thall     output   
 Min.   :0.000   Type 0: 21   Type 0:175   Type 0:  2   No :164  
 1st Qu.:0.000   Type 1:140   Type 1: 65   Type 1: 18   Yes:138  
 Median :0.800   Type 2:141   Type 2: 38   Type 2:165            
 Mean   :1.043                Type 3: 20   Type 3:117            
 3rd Qu.:1.600                Type 4:  4                         
 Max.   :6.200                                                   </code></pre>
</div>
</div>
<p>Looks more organize and better for our analysis later</p>
</section>
<section id="data-exploration" class="level1">
<h1>Data exploration</h1>
<p>Histogram for numerical variables and barplot for categorical variables</p>
<p>Numerical: age</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(age)) <span class="sc">+</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>trtbps</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(trtbps)) <span class="sc">+</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>chol</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(chol)) <span class="sc">+</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>thalachh</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(thalachh)) <span class="sc">+</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>oldpeak</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(oldpeak)) <span class="sc">+</span> </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Categorical:</p>
<p>sex</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(sex)) <span class="sc">+</span> </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>cp</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(cp)) <span class="sc">+</span> </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>fbs</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(fbs)) <span class="sc">+</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>restecg</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(restecg)) <span class="sc">+</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>exng</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(exng)) <span class="sc">+</span> </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>slp</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(slp)) <span class="sc">+</span> </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>caa</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(caa)) <span class="sc">+</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>thall</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(thall)) <span class="sc">+</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>output</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(heart1, <span class="fu">aes</span>(<span class="at">x =</span> output)) <span class="sc">+</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Output Distribution"</span>, <span class="at">x =</span> <span class="st">"Output"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We assume the output of our findings follow Bernoulli distribution. Hence, we are using Multiple Logistic Regression as our statistical analysis.</p>
<section id="estimation" class="level2">
<h2 class="anchored" data-anchor-id="estimation">Estimation</h2>
<p>Simple Logistic Regression Numerical: age, trtbps, chol, thalachh, oldpeak</p>
<p>1 Age</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>slr.age <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> age, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ age, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -2.98760    0.75897  -3.936 8.27e-05 ***
age          0.05153    0.01367   3.770 0.000163 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 401.26  on 300  degrees of freedom
AIC: 405.26

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>2 Resting Blood Pressure</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>slr.trtbps <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> trtbps, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.trtbps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ trtbps, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept) -2.421015   0.904644  -2.676  0.00745 **
trtbps       0.017067   0.006807   2.507  0.01217 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 409.91  on 300  degrees of freedom
AIC: 413.91

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>3 Cholesterol level</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>slr.chol <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> chol, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.chol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ chol, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) -0.959845   0.572724  -1.676   0.0938 .
chol         0.003191   0.002272   1.404   0.1603  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 414.41  on 300  degrees of freedom
AIC: 418.41

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>4 Maximum heart rate achieved</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>slr.thalachh <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> thalachh, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.thalachh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ thalachh, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  6.361133   0.986817   6.446 1.15e-10 ***
thalachh    -0.043724   0.006531  -6.695 2.16e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 358.73  on 300  degrees of freedom
AIC: 362.73

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>5 Previous peak in ECG</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>slr.oldpeak <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> oldpeak, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.oldpeak)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ oldpeak, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.1096     0.1812  -6.124 9.13e-10 ***
oldpeak       0.9352     0.1386   6.749 1.49e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 354.43  on 300  degrees of freedom
AIC: 358.43

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Categorical: sex, ep, fbs, restecg, exng, slp, caa, thall we are not using tidy to standardized our SLogR presentation. tidy mode looks cleaner but summary gave more info</p>
<p>1 Sex</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>slr.sex <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> sex, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ sex, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.0986     0.2357  -4.661 3.15e-06 ***
sexMale       1.3130     0.2742   4.788 1.68e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 391.19  on 300  degrees of freedom
AIC: 395.19

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>2 Chest pain type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>slr.cp <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> cp, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.cp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ cp, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   0.9808     0.1878   5.224 1.75e-07 ***
cpType 1     -2.4972     0.4132  -6.043 1.51e-09 ***
cpType 2     -2.3100     0.3248  -7.111 1.15e-12 ***
cpType 3     -1.8075     0.4905  -3.685 0.000229 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 331.23  on 298  degrees of freedom
AIC: 339.23

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>3 Fasting blood sugar</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>slr.fbs <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> fbs, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.fbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ fbs, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)  -0.1952     0.1254  -1.557    0.119
fbsTrue       0.1507     0.3235   0.466    0.641

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 416.20  on 300  degrees of freedom
AIC: 420.2

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
<p>4 Resting ECG</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>slr.restecg <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> restecg, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.restecg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ restecg, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)     0.1499     0.1654   0.906  0.36472   
restecgType 1  -0.6785     0.2361  -2.874  0.00406 **
restecgType 2   0.9487     1.1665   0.813  0.41606   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 406.60  on 299  degrees of freedom
AIC: 412.6

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>5 Exercise Induced Angina</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>slr.exng <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> exng, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.exng)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ exng, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -0.8216     0.1524  -5.392 6.98e-08 ***
exngYes       2.0169     0.2826   7.137 9.53e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 357.18  on 300  degrees of freedom
AIC: 361.18

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>6 Slope</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>slr.slp <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> slp, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.slp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ slp, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)   0.2877     0.4410   0.652  0.51414   
slpType 1     0.3314     0.4752   0.697  0.48564   
slpType 2    -1.3958     0.4821  -2.895  0.00379 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 367.99  on 299  degrees of freedom
AIC: 373.99

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>7 Number of Major Vessels</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>slr.caa <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> caa, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.caa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ caa, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.06087    0.17296  -6.134 8.59e-10 ***
caaType 1    1.80054    0.31664   5.686 1.30e-08 ***
caaType 2    2.54895    0.45280   5.629 1.81e-08 ***
caaType 3    2.79547    0.64967   4.303 1.69e-05 ***
caaType 4   -0.03774    1.16758  -0.032    0.974    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 339.02  on 297  degrees of freedom
AIC: 349.02

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>8 Thalium Stress test result</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>slr.thall <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> thall, <span class="at">data =</span> heart1, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slr.thall)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ thall, family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)  4.462e-14  1.414e+00   0.000    1.000
thallType 1  6.931e-01  1.500e+00   0.462    0.644
thallType 2 -1.276e+00  1.427e+00  -0.895    0.371
thallType 3  1.156e+00  1.431e+00   0.808    0.419

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 327.57  on 298  degrees of freedom
AIC: 335.57

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>From the univariable analysis, we built our model using clinically significant data, data which is highly spelled out in literature and clinical expert opinion.</p>
</section>
</section>
<section id="multiple-logistic-regression" class="level1">
<h1>Multiple Logistic Regression</h1>
<p>More than one independent covariates (predictors)</p>
<p>We estimate the logit or the log odds. We used summary to see the results stored as mylogit We used coefficients to examine the regression coefficients</p>
</section>
<section id="model-a-multiple-logistic-regression-model-without-interaction" class="level1">
<h1>Model A : Multiple logistic regression model without interaction</h1>
<p>Predictors : age, sex, chest pain type, resting blood pressure, fasting blood sugar and exercise induced angina Outcome : Heart Attack</p>
<p>Justification of this model: All the variables is available in basic healthcare facilities.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>mlr.age.sex.cp.trtbps.fbs.exng <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> cp <span class="sc">+</span> trtbps <span class="sc">+</span> fbs <span class="sc">+</span> exng,<span class="at">family =</span> <span class="st">'binomial'</span>(<span class="at">link =</span> logit), </span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> heart1)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlr.age.sex.cp.trtbps.fbs.exng)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ age + sex + cp + trtbps + fbs + exng, 
    family = binomial(link = logit), data = heart1)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -6.165134   1.481285  -4.162 3.15e-05 ***
age          0.056738   0.018433   3.078 0.002083 ** 
sexMale      1.749190   0.364109   4.804 1.56e-06 ***
cpType 1    -2.061457   0.472763  -4.360 1.30e-05 ***
cpType 2    -1.986263   0.382389  -5.194 2.05e-07 ***
cpType 3    -2.055228   0.555888  -3.697 0.000218 ***
trtbps       0.017276   0.008928   1.935 0.052978 .  
fbsTrue     -0.033273   0.427426  -0.078 0.937952    
exngYes      1.207781   0.342385   3.528 0.000419 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 274.96  on 293  degrees of freedom
AIC: 292.96

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>Better visualize with tidy</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mlr.age.sex.cp.trtbps.fbs.exng,</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 7
  term        estimate std.error statistic     p.value   conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)  -6.17     1.48      -4.16   0.0000315   -9.17        -3.34  
2 age           0.0567   0.0184     3.08   0.00208      0.0213       0.0938
3 sexMale       1.75     0.364      4.80   0.00000156   1.06         2.49  
4 cpType 1     -2.06     0.473     -4.36   0.0000130   -3.04        -1.17  
5 cpType 2     -1.99     0.382     -5.19   0.000000205 -2.76        -1.26  
6 cpType 3     -2.06     0.556     -3.70   0.000218    -3.20        -1.00  
7 trtbps        0.0173   0.00893    1.94   0.0530       0.0000271    0.0352
8 fbsTrue      -0.0333   0.427     -0.0778 0.938       -0.879        0.803 
9 exngYes       1.21     0.342      3.53   0.000419     0.542        1.89  </code></pre>
</div>
</div>
<p>Calculating the odds ratios and their confidence intervals To obtain the odds ratios and their 95% CI, we need to exponentiate using exp the regression coefficients or the betas just exponentiate</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mlr.age.sex.cp.trtbps.fbs.exng, </span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, </span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 7
  term        estimate std.error statistic     p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)  0.00210   1.48      -4.16   0.0000315   0.000104    0.0355
2 age          1.06      0.0184     3.08   0.00208     1.02        1.10  
3 sexMale      5.75      0.364      4.80   0.00000156  2.88       12.1   
4 cpType 1     0.127     0.473     -4.36   0.0000130   0.0480      0.310 
5 cpType 2     0.137     0.382     -5.19   0.000000205 0.0632      0.285 
6 cpType 3     0.128     0.556     -3.70   0.000218    0.0408      0.368 
7 trtbps       1.02      0.00893    1.94   0.0530      1.00        1.04  
8 fbsTrue      0.967     0.427     -0.0778 0.938       0.415       2.23  
9 exngYes      3.35      0.342      3.53   0.000419    1.72        6.62  </code></pre>
</div>
</div>
<p>We are not yet finish. Proceed with model B.</p>
</section>
<section id="model-b-multiple-logistic-regression-model-with-interaction" class="level1">
<h1>Model B : Multiple logistic regression model with interaction</h1>
<p>Predictors : age, sex, chest pain type, resting blood pressure, fasting blood sugar, exercise induced angina AND sex*fbs Outcome : Heart Attack</p>
<p>Interactions in statistical models signify that the effect of multivariable on the outcome; heart attack event depends on the value of another variable which is context of sex and fasting blood sugar</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>mlr.age.sex.cp.trtbps.fbs.exng.int <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> cp <span class="sc">+</span> trtbps <span class="sc">+</span> fbs <span class="sc">+</span> exng <span class="sc">+</span> sex<span class="sc">*</span>fbs,<span class="at">family =</span> <span class="st">'binomial'</span>(<span class="at">link =</span> logit), </span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> heart1)</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlr.age.sex.cp.trtbps.fbs.exng.int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ age + sex + cp + trtbps + fbs + exng + 
    sex * fbs, family = binomial(link = logit), data = heart1)

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     -6.56720    1.53164  -4.288 1.81e-05 ***
age              0.06001    0.01882   3.188 0.001433 ** 
sexMale          2.05534    0.40450   5.081 3.75e-07 ***
cpType 1        -2.15035    0.47979  -4.482 7.40e-06 ***
cpType 2        -2.00113    0.38520  -5.195 2.05e-07 ***
cpType 3        -2.08739    0.55734  -3.745 0.000180 ***
trtbps           0.01750    0.00909   1.926 0.054150 .  
fbsTrue          1.40674    0.81394   1.728 0.083933 .  
exngYes          1.18057    0.34429   3.429 0.000606 ***
sexMale:fbsTrue -1.90905    0.94663  -2.017 0.043729 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 271.00  on 292  degrees of freedom
AIC: 291

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>It shows the interaction of the model with sex and fbs is significant. Thus, we keep model B.</p>
</section>
<section id="inference" class="level1">
<h1>Inference</h1>
<p>Likelihood ratio test. We compare between Model A and B using anova.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mlr.age.sex.cp.trtbps.fbs.exng, mlr.age.sex.cp.trtbps.fbs.exng.int, </span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">test =</span> <span class="st">'Chisq'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: output ~ age + sex + cp + trtbps + fbs + exng
Model 2: output ~ age + sex + cp + trtbps + fbs + exng + sex * fbs
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)  
1       293     274.96                       
2       292     271.00  1    3.959  0.04662 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The p-value of 0.04662 associated with the change in deviance suggests that adding the interaction term does significantly improve the fit of Model B compared to Model A. So, we choose Model B with interaction as our preliminary final model.</p>
</section>
<section id="model-selection" class="level1">
<h1>Model Selection</h1>
<p>Correlation matrix</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>corr.num <span class="ot">&lt;-</span> heart1 <span class="sc">%&gt;%</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(age, chol, trtbps, thalachh, oldpeak) <span class="sc">%&gt;%</span></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">use =</span> <span class="st">'complete.obs'</span>)</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>corr.num</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                age         chol      trtbps     thalachh     oldpeak
age       1.0000000  0.207215506  0.28312068 -0.395235188  0.20603964
chol      0.2072155  1.000000000  0.12525629 -0.005308496  0.05008602
trtbps    0.2831207  0.125256286  1.00000000 -0.048022712  0.19459995
thalachh -0.3952352 -0.005308496 -0.04802271  1.000000000 -0.34220075
oldpeak   0.2060396  0.050086024  0.19459995 -0.342200746  1.00000000</code></pre>
</div>
</div>
<p>Easier to view in Correlogram</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(corr.num, <span class="at">type =</span> <span class="st">'upper'</span>, <span class="at">order =</span> <span class="st">'hclust'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>No significant correlation detected</p>
</section>
<section id="prediction" class="level1">
<h1>Prediction</h1>
<p>We took Model B (MLR model with interaction) as our preliminary model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>final.m <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> cp <span class="sc">+</span> trtbps <span class="sc">+</span> fbs <span class="sc">+</span> exng <span class="sc">+</span> sex<span class="sc">*</span>fbs, <span class="at">family =</span> binomial,</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> heart1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Predicted log odds</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(final.m, </span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 7
   term            estimate std.error statistic     p.value   conf.low conf.high
   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)      -6.57     1.53        -4.29 0.0000181   -9.68        -3.65  
 2 age               0.0600   0.0188       3.19 0.00143      0.0239       0.0979
 3 sexMale           2.06     0.404        5.08 0.000000375  1.29         2.88  
 4 cpType 1         -2.15     0.480       -4.48 0.00000740  -3.14        -1.25  
 5 cpType 2         -2.00     0.385       -5.20 0.000000205 -2.78        -1.27  
 6 cpType 3         -2.09     0.557       -3.75 0.000180    -3.24        -1.03  
 7 trtbps            0.0175   0.00909      1.93 0.0542      -0.0000459    0.0358
 8 fbsTrue           1.41     0.814        1.73 0.0839      -0.232        2.99  
 9 exngYes           1.18     0.344        3.43 0.000606     0.511        1.87  
10 sexMale:fbsTrue  -1.91     0.947       -2.02 0.0437      -3.77        -0.0290</code></pre>
</div>
</div>
<p>Predicted odds</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(final.m, </span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">exponentiate =</span> <span class="cn">TRUE</span>,</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 7
   term            estimate std.error statistic     p.value  conf.low conf.high
   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)      0.00141   1.53        -4.29 0.0000181   0.0000624    0.0259
 2 age              1.06      0.0188       3.19 0.00143     1.02         1.10  
 3 sexMale          7.81      0.404        5.08 0.000000375 3.63        17.8   
 4 cpType 1         0.116     0.480       -4.48 0.00000740  0.0433       0.288 
 5 cpType 2         0.135     0.385       -5.20 0.000000205 0.0620       0.282 
 6 cpType 3         0.124     0.557       -3.75 0.000180    0.0394       0.357 
 7 trtbps           1.02      0.00909      1.93 0.0542      1.00         1.04  
 8 fbsTrue          4.08      0.814        1.73 0.0839      0.793       19.9   
 9 exngYes          3.26      0.344        3.43 0.000606    1.67         6.46  
10 sexMale:fbsTrue  0.148     0.947       -2.02 0.0437      0.0231       0.971 </code></pre>
</div>
</div>
</section>
<section id="fitted-values" class="level1">
<h1>Fitted values</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(final.m, </span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">type.predict =</span> <span class="st">'response'</span>, </span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">type.residuals =</span> <span class="st">'pearson'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 302 × 14
   .rownames output   age sex    cp    trtbps fbs   exng  .fitted .resid    .hat
   &lt;chr&gt;     &lt;fct&gt;  &lt;int&gt; &lt;fct&gt;  &lt;fct&gt;  &lt;int&gt; &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
 1 1         No        63 Male   Type…    145 True  No     0.314  -0.676 0.0835 
 2 2         No        37 Male   Type…    130 False No     0.117  -0.365 0.0214 
 3 3         No        41 Female Type…    130 False No     0.0183 -0.137 0.00716
 4 4         No        56 Male   Type…    120 False No     0.231  -0.548 0.0332 
 5 5         No        57 Female Type…    120 False Yes    0.533  -1.07  0.0406 
 6 6         No        57 Male   Type…    140 False No     0.796  -1.97  0.0175 
 7 7         No        56 Female Type…    140 False No     0.0518 -0.234 0.0138 
 8 8         No        44 Male   Type…    120 False No     0.128  -0.383 0.0232 
 9 9         No        52 Male   Type…    172 True  No     0.292  -0.643 0.0728 
10 10        No        57 Male   Type…    150 False No     0.385  -0.792 0.0334 
# ℹ 292 more rows
# ℹ 3 more variables: .sigma &lt;dbl&gt;, .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="model-checking" class="level1">
<h1>Model Checking</h1>
<p>Overall fitness</p>
<p>accuracy</p>
<p>sensitivity</p>
<p>specificity</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>final.m.prob <span class="ot">&lt;-</span> </span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(final.m, </span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">type.predict =</span> <span class="st">'response'</span>) <span class="sc">|&gt;</span></span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred.class =</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(.fitted <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">'Yes'</span>, <span class="st">'No'</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>final.m.prob<span class="sc">$</span>output <span class="ot">&lt;-</span> <span class="fu">factor</span>(final.m.prob<span class="sc">$</span>output, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'Yes'</span>, <span class="st">'No'</span>))</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>final.m.prob<span class="sc">$</span>pred.class <span class="ot">&lt;-</span> <span class="fu">factor</span>(final.m.prob<span class="sc">$</span>pred.class, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'Yes'</span>, <span class="st">'No'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(final.m.prob<span class="sc">$</span>output, final.m.prob<span class="sc">$</span>pred.class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction Yes  No
       Yes 101  37
       No   27 137
                                          
               Accuracy : 0.7881          
                 95% CI : (0.7376, 0.8328)
    No Information Rate : 0.5762          
    P-Value [Acc &gt; NIR] : 6.825e-15       
                                          
                  Kappa : 0.5705          
                                          
 Mcnemar's Test P-Value : 0.2606          
                                          
            Sensitivity : 0.7891          
            Specificity : 0.7874          
         Pos Pred Value : 0.7319          
         Neg Pred Value : 0.8354          
             Prevalence : 0.4238          
         Detection Rate : 0.3344          
   Detection Prevalence : 0.4570          
      Balanced Accuracy : 0.7882          
                                          
       'Positive' Class : Yes             
                                          </code></pre>
</div>
</div>
<p>The model has an overall accuracy of 78.81%, model able to predict correctly 78.81% of the cases.</p>
<p>Sensitivity (True Positive Rate) is at 78.91%, indicating that the model is good at capturing all positive cases.</p>
<p>Specificity (True Negative Rate) is higher at 78.74%, indicating good performance in correctly identifying negative cases.</p>
</section>
<section id="linearity-of-logit" class="level1">
<h1>Linearity of Logit</h1>
<p>All numerical covariates should be checked for linearity in logits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mfp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'mfp' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: survival</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'survival' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'survival'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked _by_ '.GlobalEnv':

    heart</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:caret':

    cluster</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>lin.age.trtbps <span class="ot">&lt;-</span> </span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mfp</span>(output <span class="sc">~</span> <span class="fu">fp</span>(age) <span class="sc">+</span> <span class="fu">fp</span>(trtbps),</span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">'logit'</span>),</span>
<span id="cb123-4"><a href="#cb123-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> heart1, <span class="at">verbose =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Variable    Deviance    Power(s)
------------------------------------------------
Cycle 1
    age              
                409.907      
                398.903     1
                397.397     -2
                393.962     3 3

    trtbps               
                401.255      
                398.903     1
                398.67      3
                398.503     3 3


Tansformation
       shift scale
age        0   100
trtbps     0   100

Fractional polynomials
       df.initial select alpha df.final power1 power2
age             4      1  0.05        1      1      .
trtbps          4      1  0.05        1      1      .


Transformations of covariates:
                 formula
age       I((age/100)^1)
trtbps I((trtbps/100)^1)


Deviance table:
         Resid. Dev
Null model   416.4197
Linear model     398.9035
Final model  398.9035</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lin.age.trtbps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ I((age/100)^1) + I((trtbps/100)^1), family = binomial(link = "logit"), 
    data = heart1)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)        -4.0943     1.0594  -3.865 0.000111 ***
I((age/100)^1)      4.5760     1.4127   3.239 0.001199 ** 
I((trtbps/100)^1)   1.0792     0.7089   1.522 0.127911    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 416.42  on 301  degrees of freedom
Residual deviance: 398.90  on 299  degrees of freedom
AIC: 404.9

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>The transformed age variable has a significant impact on the response variable. The transformed trtbps variable is not statistically significant at the 0.05 significance level.</p>
</section>
<section id="diagnostics-plots" class="level1">
<h1>Diagnostics plots</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(generalhoslem)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'generalhoslem' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: reshape</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'reshape' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'reshape'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:lubridate':

    stamp</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    rename</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:tidyr':

    expand, smiths</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:gtsummary':

    select</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ResourceSelection' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>ResourceSelection 0.3-6      2023-06-27</code></pre>
</div>
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROCR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ROCR' was built under R version 4.3.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'pROC' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Type 'citation("pROC")' for a citation.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'pROC'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    cov, smooth, var</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logitgof</span>(heart1<span class="sc">$</span>output, <span class="fu">fitted</span>(final.m), <span class="at">g =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in logitgof(heart1$output, fitted(final.m), g = 10): At least one cell
in the expected frequencies table is &lt; 1. Chi-square approximation may be
incorrect.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Hosmer and Lemeshow test (binary model)

data:  heart1$output, fitted(final.m)
X-squared = 2.3091, df = 8, p-value = 0.97</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hoslem.test</span>(heart1<span class="sc">$</span>output, <span class="fu">fitted</span>(final.m), <span class="at">g =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in Ops.factor(1, y): '-' not meaningful for factors</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Hosmer and Lemeshow goodness of fit (GOF) test

data:  heart1$output, fitted(final.m)
X-squared = 302, df = 8, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There is discrepancy between the results could be due to variations in the statistical methodology or algorithms used by each function to calculate the Hosmer-Lemeshow test statistic could lead to different results. Educated guess: low expected frequencies in variable of type of chest pain.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(output <span class="sc">~</span> <span class="fu">predict</span>(final.m, <span class="at">type =</span> <span class="st">"response"</span>), <span class="at">data =</span> heart1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = No, case = Yes</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb158"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb158-1"><a href="#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(roc_curve)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.8712</code></pre>
</div>
<div class="sourceCode cell-code" id="cb160"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb160-1"><a href="#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_curve, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">main =</span> <span class="st">"ROC Curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Area under Receiver of Operating Characteristic Curve (AUC-ROC):</p>
<p>AUC-ROC is 87.12%, the model is considered good discriminating effect.</p>
<p>Hence, all of above goodness of fit test shows that our model has good fit.</p>
</section>
<section id="prelim-final-plots" class="level1">
<h1>Prelim final plots</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(final.m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-60-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-60-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-60-4.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="influential" class="level1">
<h1>Influential</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb162"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb162-1"><a href="#cb162-1" aria-hidden="true" tabindex="-1"></a>infl <span class="ot">&lt;-</span> <span class="fu">influence.measures</span>(final.m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We use augment() to generate the residuals values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb163"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb163-1"><a href="#cb163-1" aria-hidden="true" tabindex="-1"></a>data2.pred.res <span class="ot">&lt;-</span> <span class="fu">augment</span>(final.m)</span>
<span id="cb163-2"><a href="#cb163-2" aria-hidden="true" tabindex="-1"></a>data2.pred.res</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 302 × 14
   .rownames output   age sex    cp    trtbps fbs   exng  .fitted .resid    .hat
   &lt;chr&gt;     &lt;fct&gt;  &lt;int&gt; &lt;fct&gt;  &lt;fct&gt;  &lt;int&gt; &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
 1 1         No        63 Male   Type…    145 True  No     -0.783 -0.868 0.0835 
 2 2         No        37 Male   Type…    130 False No     -2.02  -0.500 0.0214 
 3 3         No        41 Female Type…    130 False No     -3.98  -0.192 0.00716
 4 4         No        56 Male   Type…    120 False No     -1.20  -0.725 0.0332 
 5 5         No        57 Female Type…    120 False Yes     0.134 -1.23  0.0406 
 6 6         No        57 Male   Type…    140 False No      1.36  -1.78  0.0175 
 7 7         No        56 Female Type…    140 False No     -2.91  -0.326 0.0138 
 8 8         No        44 Male   Type…    120 False No     -1.92  -0.523 0.0232 
 9 9         No        52 Male   Type…    172 True  No     -0.884 -0.831 0.0728 
10 10        No        57 Male   Type…    150 False No     -0.467 -0.986 0.0334 
# ℹ 292 more rows
# ℹ 3 more variables: .sigma &lt;dbl&gt;, .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Method : Standardized residuals Keep standardized residuals between 2 and -2 (values above 2 or lower than −2 considered as influential observations)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb165"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb165-1"><a href="#cb165-1" aria-hidden="true" tabindex="-1"></a>non.influen.obs <span class="ot">&lt;-</span> </span>
<span id="cb165-2"><a href="#cb165-2" aria-hidden="true" tabindex="-1"></a>  data2.pred.res <span class="sc">%&gt;%</span> </span>
<span id="cb165-3"><a href="#cb165-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.std.resid <span class="sc">&lt;</span> <span class="dv">2</span> <span class="sc">&amp;</span> .std.resid <span class="sc">&gt;</span> <span class="sc">-</span><span class="dv">2</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Re-run the Model with the non-influential observations (final model)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb166"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb166-1"><a href="#cb166-1" aria-hidden="true" tabindex="-1"></a>final.m1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(output <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> cp <span class="sc">+</span> trtbps <span class="sc">+</span> fbs <span class="sc">+</span> exng <span class="sc">+</span> sex<span class="sc">*</span>fbs, <span class="at">data =</span> non.influen.obs, <span class="at">family =</span> binomial)</span>
<span id="cb166-2"><a href="#cb166-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(final.m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = output ~ age + sex + cp + trtbps + fbs + exng + 
    sex * fbs, family = binomial, data = non.influen.obs)

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     -9.61950    1.88595  -5.101 3.39e-07 ***
age              0.08319    0.02245   3.706 0.000211 ***
sexMale          2.97270    0.50501   5.886 3.95e-09 ***
cpType 1        -2.99948    0.58113  -5.161 2.45e-07 ***
cpType 2        -2.52612    0.44303  -5.702 1.19e-08 ***
cpType 3        -2.98883    0.64296  -4.649 3.34e-06 ***
trtbps           0.02795    0.01048   2.668 0.007630 ** 
fbsTrue          2.01984    0.92950   2.173 0.029778 *  
exngYes          1.68808    0.40169   4.202 2.64e-05 ***
sexMale:fbsTrue -2.91086    1.09617  -2.655 0.007920 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 402.82  on 291  degrees of freedom
Residual deviance: 214.33  on 282  degrees of freedom
AIC: 234.33

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>Re Plot for better understanding and visualization</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb168"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb168-1"><a href="#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(final.m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-65-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-65-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="HeartAttackMLog_files/figure-html/unnamed-chunk-65-4.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="presentation" class="level1">
<h1>Presentation</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb169"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb169-1"><a href="#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_regression</span>(final.m1) <span class="sc">%&gt;%</span>  </span>
<span id="cb169-2"><a href="#cb169-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bold_labels</span>() <span class="sc">%&gt;%</span> <span class="fu">italicize_levels</span>() <span class="sc">%&gt;%</span></span>
<span id="cb169-3"><a href="#cb169-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_gt</span>() <span class="sc">%&gt;%</span></span>
<span id="cb169-4"><a href="#cb169-4" aria-hidden="true" tabindex="-1"></a>  gt<span class="sc">::</span><span class="fu">tab_header</span>(<span class="at">title =</span> <span class="st">"Multiple Logistic Regression Model"</span>,</span>
<span id="cb169-5"><a href="#cb169-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">subtitle =</span> <span class="st">"With Interaction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div id="jiuspgckgk" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#jiuspgckgk table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#jiuspgckgk thead, #jiuspgckgk tbody, #jiuspgckgk tfoot, #jiuspgckgk tr, #jiuspgckgk td, #jiuspgckgk th {
  border-style: none;
}

#jiuspgckgk p {
  margin: 0;
  padding: 0;
}

#jiuspgckgk .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#jiuspgckgk .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#jiuspgckgk .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#jiuspgckgk .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#jiuspgckgk .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jiuspgckgk .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jiuspgckgk .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jiuspgckgk .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#jiuspgckgk .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#jiuspgckgk .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#jiuspgckgk .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#jiuspgckgk .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#jiuspgckgk .gt_spanner_row {
  border-bottom-style: hidden;
}

#jiuspgckgk .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#jiuspgckgk .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#jiuspgckgk .gt_from_md > :first-child {
  margin-top: 0;
}

#jiuspgckgk .gt_from_md > :last-child {
  margin-bottom: 0;
}

#jiuspgckgk .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#jiuspgckgk .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#jiuspgckgk .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#jiuspgckgk .gt_row_group_first td {
  border-top-width: 2px;
}

#jiuspgckgk .gt_row_group_first th {
  border-top-width: 2px;
}

#jiuspgckgk .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jiuspgckgk .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#jiuspgckgk .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#jiuspgckgk .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jiuspgckgk .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jiuspgckgk .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#jiuspgckgk .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#jiuspgckgk .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#jiuspgckgk .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jiuspgckgk .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jiuspgckgk .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jiuspgckgk .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jiuspgckgk .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jiuspgckgk .gt_left {
  text-align: left;
}

#jiuspgckgk .gt_center {
  text-align: center;
}

#jiuspgckgk .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#jiuspgckgk .gt_font_normal {
  font-weight: normal;
}

#jiuspgckgk .gt_font_bold {
  font-weight: bold;
}

#jiuspgckgk .gt_font_italic {
  font-style: italic;
}

#jiuspgckgk .gt_super {
  font-size: 65%;
}

#jiuspgckgk .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#jiuspgckgk .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#jiuspgckgk .gt_indent_1 {
  text-indent: 5px;
}

#jiuspgckgk .gt_indent_2 {
  text-indent: 10px;
}

#jiuspgckgk .gt_indent_3 {
  text-indent: 15px;
}

#jiuspgckgk .gt_indent_4 {
  text-indent: 20px;
}

#jiuspgckgk .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="4" class="gt_heading gt_title gt_font_normal" style="">Multiple Logistic Regression Model</td>
    </tr>
    <tr class="gt_heading">
      <td colspan="4" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style="">With Interaction</td>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="<strong>Characteristic</strong>"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>log(OR)</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>log(OR)</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p-value</strong>"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">age</td>
<td headers="estimate" class="gt_row gt_center">0.08</td>
<td headers="ci" class="gt_row gt_center">0.04, 0.13</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">sex</td>
<td headers="estimate" class="gt_row gt_center"><br></td>
<td headers="ci" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Female</td>
<td headers="estimate" class="gt_row gt_center">—</td>
<td headers="ci" class="gt_row gt_center">—</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Male</td>
<td headers="estimate" class="gt_row gt_center">3.0</td>
<td headers="ci" class="gt_row gt_center">2.0, 4.0</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">cp</td>
<td headers="estimate" class="gt_row gt_center"><br></td>
<td headers="ci" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Type 0</td>
<td headers="estimate" class="gt_row gt_center">—</td>
<td headers="ci" class="gt_row gt_center">—</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Type 1</td>
<td headers="estimate" class="gt_row gt_center">-3.0</td>
<td headers="ci" class="gt_row gt_center">-4.2, -1.9</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Type 2</td>
<td headers="estimate" class="gt_row gt_center">-2.5</td>
<td headers="ci" class="gt_row gt_center">-3.4, -1.7</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Type 3</td>
<td headers="estimate" class="gt_row gt_center">-3.0</td>
<td headers="ci" class="gt_row gt_center">-4.3, -1.8</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">trtbps</td>
<td headers="estimate" class="gt_row gt_center">0.03</td>
<td headers="ci" class="gt_row gt_center">0.01, 0.05</td>
<td headers="p.value" class="gt_row gt_center">0.008</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">fbs</td>
<td headers="estimate" class="gt_row gt_center"><br></td>
<td headers="ci" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;False</td>
<td headers="estimate" class="gt_row gt_center">—</td>
<td headers="ci" class="gt_row gt_center">—</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;True</td>
<td headers="estimate" class="gt_row gt_center">2.0</td>
<td headers="ci" class="gt_row gt_center">0.14, 3.8</td>
<td headers="p.value" class="gt_row gt_center">0.030</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">exng</td>
<td headers="estimate" class="gt_row gt_center"><br></td>
<td headers="ci" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;No</td>
<td headers="estimate" class="gt_row gt_center">—</td>
<td headers="ci" class="gt_row gt_center">—</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Yes</td>
<td headers="estimate" class="gt_row gt_center">1.7</td>
<td headers="ci" class="gt_row gt_center">0.92, 2.5</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">sex * fbs</td>
<td headers="estimate" class="gt_row gt_center"><br></td>
<td headers="ci" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Male * True</td>
<td headers="estimate" class="gt_row gt_center">-2.9</td>
<td headers="ci" class="gt_row gt_center">-5.1, -0.74</td>
<td headers="p.value" class="gt_row gt_center">0.008</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> OR = Odds Ratio, CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb170"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb170-1"><a href="#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_regression</span>(final.m1, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span>  </span>
<span id="cb170-2"><a href="#cb170-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bold_labels</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb170-3"><a href="#cb170-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">italicize_levels</span>() <span class="sc">%&gt;%</span></span>
<span id="cb170-4"><a href="#cb170-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_gt</span>() <span class="sc">%&gt;%</span></span>
<span id="cb170-5"><a href="#cb170-5" aria-hidden="true" tabindex="-1"></a>  gt<span class="sc">::</span><span class="fu">tab_header</span>(<span class="at">title =</span> <span class="st">"Multiple Logistic Regression Model"</span>,</span>
<span id="cb170-6"><a href="#cb170-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">subtitle =</span> <span class="st">"With Interaction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div id="wstfnqnsrm" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#wstfnqnsrm table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#wstfnqnsrm thead, #wstfnqnsrm tbody, #wstfnqnsrm tfoot, #wstfnqnsrm tr, #wstfnqnsrm td, #wstfnqnsrm th {
  border-style: none;
}

#wstfnqnsrm p {
  margin: 0;
  padding: 0;
}

#wstfnqnsrm .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wstfnqnsrm .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#wstfnqnsrm .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wstfnqnsrm .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wstfnqnsrm .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wstfnqnsrm .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wstfnqnsrm .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wstfnqnsrm .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wstfnqnsrm .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wstfnqnsrm .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wstfnqnsrm .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wstfnqnsrm .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wstfnqnsrm .gt_spanner_row {
  border-bottom-style: hidden;
}

#wstfnqnsrm .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#wstfnqnsrm .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#wstfnqnsrm .gt_from_md > :first-child {
  margin-top: 0;
}

#wstfnqnsrm .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wstfnqnsrm .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wstfnqnsrm .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#wstfnqnsrm .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#wstfnqnsrm .gt_row_group_first td {
  border-top-width: 2px;
}

#wstfnqnsrm .gt_row_group_first th {
  border-top-width: 2px;
}

#wstfnqnsrm .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wstfnqnsrm .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#wstfnqnsrm .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#wstfnqnsrm .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wstfnqnsrm .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wstfnqnsrm .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wstfnqnsrm .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#wstfnqnsrm .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wstfnqnsrm .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wstfnqnsrm .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wstfnqnsrm .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wstfnqnsrm .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wstfnqnsrm .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wstfnqnsrm .gt_left {
  text-align: left;
}

#wstfnqnsrm .gt_center {
  text-align: center;
}

#wstfnqnsrm .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wstfnqnsrm .gt_font_normal {
  font-weight: normal;
}

#wstfnqnsrm .gt_font_bold {
  font-weight: bold;
}

#wstfnqnsrm .gt_font_italic {
  font-style: italic;
}

#wstfnqnsrm .gt_super {
  font-size: 65%;
}

#wstfnqnsrm .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#wstfnqnsrm .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#wstfnqnsrm .gt_indent_1 {
  text-indent: 5px;
}

#wstfnqnsrm .gt_indent_2 {
  text-indent: 10px;
}

#wstfnqnsrm .gt_indent_3 {
  text-indent: 15px;
}

#wstfnqnsrm .gt_indent_4 {
  text-indent: 20px;
}

#wstfnqnsrm .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="4" class="gt_heading gt_title gt_font_normal" style="">Multiple Logistic Regression Model</td>
    </tr>
    <tr class="gt_heading">
      <td colspan="4" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style="">With Interaction</td>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="<strong>Characteristic</strong>"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>OR</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>OR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p-value</strong>"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">age</td>
<td headers="estimate" class="gt_row gt_center">1.09</td>
<td headers="ci" class="gt_row gt_center">1.04, 1.14</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">sex</td>
<td headers="estimate" class="gt_row gt_center"><br></td>
<td headers="ci" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Female</td>
<td headers="estimate" class="gt_row gt_center">—</td>
<td headers="ci" class="gt_row gt_center">—</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Male</td>
<td headers="estimate" class="gt_row gt_center">19.5</td>
<td headers="ci" class="gt_row gt_center">7.63, 55.7</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">cp</td>
<td headers="estimate" class="gt_row gt_center"><br></td>
<td headers="ci" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Type 0</td>
<td headers="estimate" class="gt_row gt_center">—</td>
<td headers="ci" class="gt_row gt_center">—</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Type 1</td>
<td headers="estimate" class="gt_row gt_center">0.05</td>
<td headers="ci" class="gt_row gt_center">0.01, 0.15</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Type 2</td>
<td headers="estimate" class="gt_row gt_center">0.08</td>
<td headers="ci" class="gt_row gt_center">0.03, 0.18</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Type 3</td>
<td headers="estimate" class="gt_row gt_center">0.05</td>
<td headers="ci" class="gt_row gt_center">0.01, 0.17</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">trtbps</td>
<td headers="estimate" class="gt_row gt_center">1.03</td>
<td headers="ci" class="gt_row gt_center">1.01, 1.05</td>
<td headers="p.value" class="gt_row gt_center">0.008</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">fbs</td>
<td headers="estimate" class="gt_row gt_center"><br></td>
<td headers="ci" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;False</td>
<td headers="estimate" class="gt_row gt_center">—</td>
<td headers="ci" class="gt_row gt_center">—</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;True</td>
<td headers="estimate" class="gt_row gt_center">7.54</td>
<td headers="ci" class="gt_row gt_center">1.15, 45.5</td>
<td headers="p.value" class="gt_row gt_center">0.030</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">exng</td>
<td headers="estimate" class="gt_row gt_center"><br></td>
<td headers="ci" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;No</td>
<td headers="estimate" class="gt_row gt_center">—</td>
<td headers="ci" class="gt_row gt_center">—</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Yes</td>
<td headers="estimate" class="gt_row gt_center">5.41</td>
<td headers="ci" class="gt_row gt_center">2.51, 12.2</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-weight: bold;">sex * fbs</td>
<td headers="estimate" class="gt_row gt_center"><br></td>
<td headers="ci" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left" style="font-style: italic;">&nbsp;&nbsp;&nbsp;&nbsp;Male * True</td>
<td headers="estimate" class="gt_row gt_center">0.05</td>
<td headers="ci" class="gt_row gt_center">0.01, 0.48</td>
<td headers="p.value" class="gt_row gt_center">0.008</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> OR = Odds Ratio, CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
</section>
<section id="interpretation" class="level1">
<h1>Interpretation</h1>
<p>log[p/(1-p)] = B0 + B1x …. B(interaction)x + SE</p>
<p>log[p/(1-p)] = 9.61950 + age(0.08) + sexMale(3.00) + cpType1(-3.0) + cpType2(-2.5) + cpType3(-3.0) + trtbps(0.03) + fbs(2.0) + exng(1.7) + sex*fbs(-2.9)</p>
<p>With one year increase of age, the odds for heart attack increase by 1.09 with 95% CI 1.04-1.14, when adjusting to other covariates or in other words, increase risk by 9%.</p>
<p>Being male, has odds of 19.5 of having heart attack with 95% CI 7.63, 55.7 as compared to female and after adjusting with other variables.</p>
<p>Chest pain type 1 (atypical angina) has odds of 0.05 for heart attack event while chest pain type 2 (non angina) has odds of 0.08 and chest pain type 3 (asympyomatic) has odds of 0.05 compared to Type 0(typical angina pain) after adjusting with other covariates with 95% CI 0.01, 0.15 , 0.03, 0.18 and 0.01, 0.17 respectively.</p>
<p>1 mmHg increase of resting blood pressure will increase odds of having heart attack by 1.03 with 95% CI 1.01, 1.05 after adjusting with other variables.</p>
<p>Fasting blood sugar more than 6.7mmol/l have odds of heart attack by 7.54 with 95% CI 1.15, 45.5 after adjusting with other variables.</p>
<p>Person with exercise induce angina has odds of heart attack by 5.41 with 95% CI 2.51, 12.2 after adjusting with other variables.</p>
<p>Male patient with FBS more than 6.7mmol/L has odds of heart attack 0.05 with 95% CI of 0.01-0.48 after adjusting to other covariates when inferring to the this study population. Explanation: maybe male with DM is more likely to develop silent heart attack due to recall bias or interview bias</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>